### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by HashiSlashi** [KMKINGMAN/Application-Bot#7]
/home/container/node_modules/discord.js/src/client/Client.js:206
    if (!token || typeof token !== 'string') throw new Error('TOKEN_INVALID');
                                                   ^
Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (/home/container/node_modules/discord.js/src/client/Client.js:206:52)
    at Object.<anonymous> (/home/container/index.js:46:8)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'TOKEN_INVALID

**Comment by jacobharr24** [comment]
did u fuiger it out
